const info = [
  {
    id: 1,
    alt: "home",
    text: "Домой",
    src: "assets/home.png",
    anchor: "/HomePage",
    srcCard: "",
  },
  {
    id: 2,
    alt: "search",
    text: "Поиск",
    src: "assets/search.png",
    anchor: "/SearchPage",
    srcCard: "assets/bg_search.png",
  },
  {
    id: 3,
    alt: "rush",
    text: "Срочные заказы",
    src: "assets/timer.png",
    anchor: "/RushPage",
    srcCard: "assets/bg_rush.png",
  },
  {
    id: 4,
    alt: "plan",
    text: "Плановые заказы",
    src: "assets/plan.png",
    anchor: "/PlanPage",
    srcCard: "assets/bg_plan.png",
  },
  {
    id: 5,
    alt: "supplier",
    text: "Заказы поставщику",
    src: "assets/delivery.png",
    anchor: "/SupplierPage",
    srcCard: "assets/bg_supplier.png",
  },
  {
    id: 6,
    alt: "incoming",
    text: "Приходные накладные",
    src: "assets/incoming.png",
    anchor: "/IncomingPage",
    srcCard: "assets/bg_incoming.png",
  },
  {
    id: 7,
    alt: "analytics",
    text: "Аналитика",
    src: "assets/chart.png",
    anchor: "/AnalyticsPage",
    srcCard: "assets/bg_analytics.png",
  },
];

export default info;
